---

#         _\|/_
#         (o o)
# +----oOO-{_}-OOo-----------------------------------------------------------------+
# |Double Crystal-ball parameters expressed as a function of mH around mH : 125 GeV|
# +--------------------------------------------------------------------------------+
#
#CATEGORY: 2e2mu

mean   : '124.812615823+(0.997287741404)*(@0-125)'
sigma  : '1.62697947135+(0.01447504986)*(@0-125)'
alpha  : '0.956199610034'
n      : '4.71386824348'
alpha2 : '1.37743809725'
n2     : '6.23835522476+(0.318139646217)*(@0-125)'

