---
##############
#Event Categorization
#Selected events are classified into 6 mutually exclusive categories, using the following criteria, in that order:

#exactly 4 leptons + at least 2 jets + at most 1 b-tag jet in the event +Djet>0.5
#       -> VBF-tagged category (#2)
#exactly 4 leptons + at least one pair of jets passing { |Î·|<2.4, pT>40, 60<mjj<120 } + pT,4l>m4l,
#       OR: exactly 4 leptons + exactly 2 jets, both with b-tag
#       -> VH-hadronic-tagged category (#4)
#no more than 2 jets + no b-tagged jet in the event; + at least 5 leptons
#       -> VH-leptonic-tagged category (#3)
#at least 3 jets, of which at least 1 b-tagged,
#       OR: at least 5 leptons
#       -> ttH-tagged category (#5)
#at least 1 jet
#       -> 1-jet-tagged category (#1)
#remaining events
#       -> untagged category (#0)

# mass window: 105 <= mass4l <= 140
# sqrt(s) = 13 TeV
# integrated luminosity = 0.90383 fb-1

mass_range: '105, 140'

UnTagged:
    ggH:    0.379725
    qqH:    0.0041643
    WH:     0.00168248
    ZH:     0.00283771
    ttH:    0.0105567
    qqZZ:   0.513184
    ggZZ:   0.0180041
    zjets:  0.234567

OneJetTagged:
    ggH:    0.225467
    qqH:    0.0271619
    WH:     0.0096906
    ZH:     0.00807988
    ttH:    0.00626811
    qqZZ:   0.150907
    ggZZ:   0.00726964
    zjets:  0.234567

VBFTagged:
    ggH:    0.0298546
    qqH:    0.0299171
    WH:     0.000759163
    ZH:     0.000615633
    ttH:    0.000829976
    qqZZ:   0.0085162
    ggZZ:   0.000743166
    zjets:  0.234567

VHLeptTagged:
    ggH:    0.00114402
    qqH:    0.000191196
    WH:     0.00261192
    ZH:     0.000329849
    ttH:    3.18047E-005
    qqZZ:   0.0042581
    ggZZ:   0.000191377
    zjets:  0.234567

VHHadrTagged:
    ggH:    0.00616009
    qqH:    0.000592709
    WH:     0.00186752
    ZH:     0.00145411
    ttH:    0.000171256
    qqZZ:   0.000681296
    ggZZ:   4.4674E-006
    zjets:  0.234567

ttHTagged:
    ggH:    0.00167202
    qqH:    0.000273411
    WH:     0.000296552
    ZH:     0.00041294
    ttH:    4.64837E-005
    qqZZ:   0.00085162
    ggZZ:   1.33485E-005
    zjets:  0.234567
