---
##############
#Event Categorization
#Selected events are classified into 6 mutually exclusive categories, using the following criteria, in that order:

#exactly 4 leptons + at least 2 jets + at most 1 b-tag jet in the event +Djet>0.5
#       -> VBF-tagged category (#2)
#exactly 4 leptons + at least one pair of jets passing { |Î·|<2.4, pT>40, 60<mjj<120 } + pT,4l>m4l,
#       OR: exactly 4 leptons + exactly 2 jets, both with b-tag
#       -> VH-hadronic-tagged category (#4)
#no more than 2 jets + no b-tagged jet in the event; + at least 5 leptons
#       -> VH-leptonic-tagged category (#3)
#at least 3 jets, of which at least 1 b-tagged,
#       OR: at least 5 leptons
#       -> ttH-tagged category (#5)
#at least 1 jet
#       -> 1-jet-tagged category (#1)
#remaining events
#       -> untagged category (#0)

# mass window: 105 <= mass4l <= 140
# sqrt(s) = 13 TeV
# integrated luminosity = 0.90383 fb-1

ggH:
    '0': 0.286649         #no_tag
    '1': 0.161523         #1jet_tag
    '2': 0.0213183        #VBF_tag
    '3': 0.000836012      #VH_leptonic_tag
    '4': 0.00440007       #VH_hadronic_tag
    '5': 0.00116602       #ttH_tag
qqH:
    '0': 0.00316816
    '1': 0.0200399
    '2': 0.0218574
    '3': 0.000139573
    '4': 0.000432105
    '5': 0.000208404
WH:
    '0': 0.00115351
    '1': 0.00704853
    '2': 0.000544207
    '3': 0.001903
    '4': 0.00131037
    '5': 0.000212095
ZH:
    '0': 0.00194131
    '1': 0.00570306
    '2': 0.000440638
    '3': 0.00024298
    '4': 0.00101851
    '5': 0.000268159
ttH:
    '0': 0.00796891
    '1': 0.00449053
    '2': 0.000592666
    '3': 2.32419e-05
    '4': 0.000122326
    '5': 3.24163e-05


qqZZ:
    '0': 0.409114
    '1': 0.121783
    '2': 0.00732393
    '3': 0.00204389
    '4': 0.00085162
    '5': 0.000510972
ggZZ:
    '0': 0.0210763
    '1': 0.00676152
    '2': 0.000622097
    '3': 0.000153368
    '4': 0
    '5': 1.75549e-05

zjets:  #mockup yields
    '0': 0.031
    '1': 0.01
    '2': 0.0002
    '3': 0.0001
    '4': 0
    '5': 1.5e-05
