
INFO: |
    - datacard inputs per category (final state) and then split to subrprocesses
    - this is a test configuration

COMMON_SETUP: &COMMON_SETUP
    words_to_be_replaced: [SQRTS, PROCESS, CATEGORY]
    reserved_sections:
        - observation
        - functions_and_definitions
        - setup
        - category
        - systematics
        - processes

    #interpreter_keywords:
        #- INSERT

    process_names: [ggH, qqH, WH, ZH, ttH, ggZZ, qqZZ, zjets]
    functions_and_definitions:
        #setup level definitions (observables, mass range, lumi,
        #whatever is common for all cards)
        - lumi_8[19.712]

