---

setup: INSERT(common_setup_8TeV.yaml:COMMON_SETUP)

category: 2e2mu_UnTagged
observation:
    #rate will be taken from the selected tree
    rate: -1
    source:
        #path given as a/b/c.root/myrootdir/mytree
        #path: inputs/data_observed_8TeV.root/passedEvents
        path: inputs/data_observed_8TeV.root/passedEvents
        selection: (mass2e2mu>105.0 && mass2e2mu<140.0)
        observables:
        #the observables names correspond to branches in tree
        #and are interpreted with RooWSFactory. This list is first to be defined.
            - mass4l[INSERT(inputs/yields_per_tag_category_13TeV_2e2mu.yaml:mass_range)]
            #- mass4l

functions_and_definitions:
    #level-0 definitions (mu, sigma, width, ...)
    - MH[125,105,140]
    - r_2e2mu[1,0,4]  #mu value

systematics: #INSERT(inputs/systematics_8TeV_2e2mu.yaml:*:UnTagged:*:*)
    - INSERT(inputs/systematics_8TeV_2e2mu.yaml:*:UnTagged:*:*)
    - INSERT(inputs/systematics_theory_8TeV_2e2mu.yaml:*:UnTagged:*:*)

processes:
    ggH:
        is_signal : 1
        #rate : 4.0230674  #TODO: get it from a dictionary
        rate : INSERT(inputs/yields_per_tag_category_13TeV_2e2mu.yaml:UnTagged:ggH)
        functions_and_definitions: &ggH_definitions
            #level-1 definitions (process norm, shape parameters, all related
            #to this process)
            - expr::ggH_norm('@0',r_2e2mu)
            - expr::mean_3_8('INSERT(inputs/signal_shape_parametrization_8TeV_2e2mu.yaml:UnTagged:mean)',MH)
            - expr::sigma_3_8('INSERT(inputs/signal_shape_parametrization_8TeV_2e2mu.yaml:UnTagged:sigma)',MH)
            - expr::alpha_3_8('0.956',MH)
            - expr::n_3_8('4.713',MH)
            - expr::alpha2_3_8('1.377',MH)
            - expr::n2_3_8('6.2383+(0.318)*(@0-125)',MH)
        shape : &ggH_shape "RooDoubleCB::ggH(mass4l, mean_3_8, sigma_3_8, alpha_3_8, n_3_8, alpha_3_8, n2_3_8)"
        systematics: #TODO
            one_extra_sys_ggH: lnN 1.03
            another_extra_sys_ggH: param 0.0 1 [-3,3]
    qqH:
        is_signal : 1
        rate : INSERT(inputs/yields_per_tag_category_13TeV_2e2mu.yaml:UnTagged:qqH)
        functions_and_definitions:
            - expr::qqH_norm('@0',r_2e2mu)
            - *ggH_definitions
        shape : "RooDoubleCB::qqH(mass4l, mean_3_8, sigma_3_8, alpha_3_8, n_3_8, alpha_3_8, n2_3_8)"
        systematics:
            one_extra_sys_ggH: lnN 1.99999
            another_extra_sys_ggH: param 0.0 1 [-9999,9999]
            lumi: lnN 2.00

    qqZZ:
        is_signal : 0
        rate : INSERT(inputs/yields_per_tag_category_13TeV_2e2mu.yaml:UnTagged:qqZZ)
        shape : Template::qqZZ(mass4l, inputs/qqZZ_2e2mu_mass4l.root/m4l_mass4l_105.6_140.6)

    ggZZ:
        is_signal : 0
        rate : INSERT(inputs/yields_per_tag_category_13TeV_2e2mu.yaml:UnTagged:ggZZ)
        shape : Template::ggZZ(mass4l, inputs/ggZZ_2e2mu_mass4l.root/m4l_mass4l_105.6_140.6)

    zjets:
        is_signal : 0
        rate : INSERT(inputs/yields_per_tag_category_13TeV_2e2mu.yaml:UnTagged:zjets)
        shape : Template::zjets(mass4l, inputs/ggZZ_2e2mu_mass4l.root/m4l_mass4l_105.6_140.6)

